name: CI

on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    branches:
      - main

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os-version: [ 'ubuntu-latest' ]
        ruby-version:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
      fail-fast: true

    runs-on: ${{ matrix.os-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run bundler-audit
        run: bundle exec bundler-audit

      # - name: Run rubocop
      #   run: bundle exec rubocop

      - name: Run rspec
        run: bundle exec rspec