name: CI

on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    branches:
      - main

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os-version: [ 'ubuntu-latest' ]
        ruby-version:
          - 3.1
          - 3.2
        include:
          - ruby-version: '3.1'
            coverage: 'true'
      fail-fast: false

    runs-on: ${{ matrix.os-version }}

    env:
      COVERAGE: "${{matrix.coverage}}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run bundler-audit
        run: |
          bundle exec bundler-audit update
          bundle exec bundler-audit

      - name: Run rspec
        env:
          OPENSSL_CONF: etc/openssl.cnf
        run: bundle exec rspec
